headers:
  - 'Accept: application/json'

options:
  - '--compress'

url: http://localhost

endpoints:
  get_ip:
    path: /ip

  get_cpu_load:
    path: /cpu/{cpu}/load
    options:
      - '--silent'

  put_cpu_load_limit:
    path: /cpu/{cpu}/load/{load}
    headers:
      - 'Content-length: 0'


requests:
  get_cpu0_load:
    endpoint: get_cpu_load
    cpu: 0

  full_local_cpu:
    endpoint: put_cpu_load_limit
    load: 100

  minimal_local_cpu:
    endpoint: put_cpu_load_limit
    load: 5
